services:
  app:
    image: reat-smart-contract
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
    networks:
      - default
networks:
  default:
    name: reatSmartContractNetwork
